imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ArticleBundle/Resources/config/services.yml" }
    - { resource: "@AdminBundle/Resources/config/services.yml" }
    - { resource: "@EventBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
vich_uploader:
    db_driver: orm
    mappings:

        articles_images:
                uri_prefix:         /images/articles
                upload_destination: '%kernel.root_dir%/../web/uploads/images/articles'
        events_images:
                uri_prefix:         /images/events
                upload_destination: '%kernel.root_dir%/../web/uploads/images/events'
        member_images:
                uri_prefix:         /images/members
                upload_destination: '%kernel.root_dir%/../web/uploads/images/members'


easy_admin:
    entities:

        Article:
            class: ArticleBundle\Entity\Article
            list:
                fields:
                - { property: 'Image', type: 'image', base_path: 'uploads/images/articles' }
                - { property: 'Owner', type: 'text' }
                - { property: 'Title', type: 'text' }
                - { property: 'Content1', type: 'text' }
                - { property: 'Content2', type: 'text' }
                - { property: 'Datecreation', type: 'datetime' }

            form:
                fields:
                    - { property: 'Owner', type: 'text' }
                    - { property: 'Title', type: 'text' }
                    - { property: 'imageFile', type: 'file' }
                    - { property: 'Content1', type: 'text' }
                    - { property: 'Content2', type: 'text' }
                    - { property: 'Datecreation', type: 'datetime' }

        Event:
            class: EventBundle\Entity\Event
            list:
                fields:
                    - { property: 'Image', type: 'image', base_path: 'uploads/images/articles' }
                    - { property: 'title', type: 'text' }
                    - { property: 'Description', type: 'text' }
                    - { property: 'SocialMediaLink', type: 'text' }
                    - { property: 'Date', type: 'datetime' }
            form:
                fields:

                    - { property: 'imageFile', type: 'file' }
                    - { property: 'title', type: 'text' }
                    - { property: 'Description', type: 'text' }
                    - { property: 'SocialMediaLink', type: 'text' }
                    - { property: 'Date', type: 'datetime' }
fos_user:

    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AdminBundle\Entity\Admin
    from_email:
        address: fghjklm
        sender_name: fghjklm