app:
    resource: "@AppBundle/Controller/"
    type:     annotation

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /event

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

article:
    resource: "@ArticleBundle/Resources/config/routing.yml"
    prefix:   /article

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
member:
    resource: "@MemberBundle/Resources/config/routing.yml"
    prefix:   /member