member_member:
    resource: "@MemberBundle/Resources/config/routing/member.yml"
    prefix:   /member

member_homepage:
    path:     /
    defaults: { _controller: MemberBundle:Default:index }
team:
    path:     /team
    defaults: { _controller: MemberBundle:Member:team }
contact:
    path:     /contact
    defaults: { _controller: MemberBundle:Member:contact }
